version: "3.8"

services:
    backend:
        build: ./blogger
        ports:
            - "5000:5000"
        volumes:
            - .:/blogger-api
        image: app:blogger-api
        container_name: blogger_api
        command: python blogger/manage.py runserver 0.0.0.0:5000

    frontend:
        build: ./frontend
        ports:
            - "5173:5173"
        volumes:
            - .:/frontend
            - /app/frontend/node_modules
        image: app:blogger
        container_name: blogger
