version: "3.8"

services:
    app:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/blogger-api
        image: app:blogger-api
        container_name: blogger_api
        command: python manage.py runserver 0.0.0.0:5000
